📄 Universal Open‑Source Attribution & Commercial License (UOSACL‑1.0)
1. Open‑Source, Personal, Research, and Educational Use
This software may be used, modified, forked, and redistributed freely for:

personal projects

academic research

teaching

open‑source contributions

non‑commercial experimentation

No fees or royalties apply for non‑commercial use.

Mandatory Attribution
Any public use, redistribution, or modification must include clear attribution:

“Original work by [kiliandiama]”

Attribution must appear in:

source code

documentation

or any public release of derivative works

2. Commercial Use
Any use of this software that generates revenue — directly or indirectly — requires a commercial license agreement with the author.

Commercial use includes:

integration into paid products or services

SaaS platforms

enterprise deployments

consulting deliverables

monetized research

derivative works used commercially

Royalties
Commercial usage is subject to royalties ranging from 8% to 30% of revenue generated by the software or its derivatives.

Terms must be negotiated with the author before commercial deployment.

Mandatory Attribution (Commercial)
Commercial users must include visible attribution in:

documentation

“About” pages

or technical credits

3. Redistribution and Integration
Redistribution — modified or unmodified — in any commercial context requires a commercial license.

Redistributors must preserve:

the author’s name or alias

the license text

the attribution clause

4. No Warranty
This software is provided “as is”, without any express or implied warranty.

The author is not liable for:

damages

data loss

financial loss

misuse

or any consequences arising from its use

5. Contact
To obtain a commercial license or negotiate royalty terms, contact:

[kiliandiama]
